# Generated by Django 4.2.4 on 2023-08-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0004_remove_exercise_targeted_muscles_and_more'),
        ('muscle_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Muscle',
        ),
    ]
