# Generated by Django 4.2.4 on 2023-08-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField()),
                ('sets', models.BigIntegerField(default=3)),
                ('reps', models.BigIntegerField(default=10)),
                ('difficulty', models.CharField()),
                ('equipment', models.CharField()),
                ('description', models.TextField()),
                ('targeted_muscles', models.CharField()),
                ('parent_workout', models.ManyToManyField(related_name='exercises', to='workout_app.workout')),
            ],
        ),
    ]
