# Generated by Django 4.2.4 on 2023-08-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout_app', '0001_initial'),
        ('exercise_app', '0001_initial'),
        ('muscle_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='parent_workout',
            field=models.ManyToManyField(related_name='exercises', to='workout_app.workout'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='targeted_muscles',
            field=models.ManyToManyField(related_name='parent_exercise', to='muscle_app.muscle'),
        ),
    ]
