# Generated by Django 4.2.4 on 2023-08-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.BigIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.BigIntegerField(default=3),
        ),
    ]
