# Generated by Django 4.2.4 on 2023-08-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='display_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
